<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>
<b>Ayush Parmar</b>
<b>23010101187</b>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

In [1]:
import numpy as np


numpy.ndarray

In [10]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
print(arr.dtype)

int32


## Create an array of 10 zeros

In [14]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [24]:
a = np.full(10,5.0)
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Create an array of the integers from 10 to 50

In [36]:
a = np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


## Create a 3x3 matrix with values ranging from 0 to 8

In [67]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Create a 3x3 identity matrix

In [65]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [63]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [91]:
a = np.arange(1,26).reshape(5,5)

m = a[2:, 1:]
print(m)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [93]:
a = np.arange(1,26).reshape(5,5)

m = a[0:3, 1:2]
print(m)

[[ 2]
 [ 7]
 [12]]


## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [99]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = arr[arr % 2==1]
print(a)

[1 3 5 7 9]


## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [122]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
m = np.vstack((a,b))
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [111]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
m = a[(a>=5) & (a<=10)]
print(m)

[ 6  9 10]


## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [114]:
A = np.random.random((5,3))
B = np.random.random((3,2))
b = np.dot(A,B)
b

array([[0.99791328, 0.71900424],
       [0.67644031, 0.42922705],
       [0.97526835, 0.88768627],
       [1.0440065 , 0.9487224 ],
       [1.17264005, 0.71310512]])

# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises

 **Context:** You are a Data Analyst at "TechCorp". 
HR has asked you to analyze employee data to understand attrition, salary trends, and job satisfaction.

**Instructions:**
1. Write your code in the empty cells.

### 1. Load & Inspect
Load `employee_data.csv` into a DataFrame named `df`. Display the first 5 rows and check column data types.

In [9]:
import pandas as pd
df = pd.read_csv("employee_data.csv")
df

EmployeeID  Age              Department            JobRole Attrition  \
0          1001   50  Research & Development     Data Scientist        No   
1          1002   36  Research & Development     Data Scientist        No   
2          1003   29                   Sales     Data Scientist        No   
3          1004   42                   Sales         Sales Exec        No   
4          1005   40                   Sales  Software Engineer        No   
..          ...  ...                     ...                ...       ...   
195        1196   40  Research & Development         Sales Exec       Yes   
196        1197   41                   Sales     Lab Technician        No   
197        1198   53  Research & Development     Data Scientist        No   
198        1199   28                   Sales  Software Engineer        No   
199        1200   54  Research & Development         Sales Exec       Yes   

     MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0             8415              19                1                  4   
1             6391              19                3                  4   
2            14157              17                1                  4   
3            14835              13                3                  4   
4             8951              16                4                  3   
..             ...             ...              ...                ...   
195           9704               7                4                  3   
196           7422              17                3                  3   
197          12984               7                3                  3   
198           4759              14                4                  3   
199          14404              15                1                  3   

     PercentSalaryHike  DistanceFromHome MaritalStatus  
0                   16                20       Married  
1                   21                21       Married  
2                   22                18       Married  
3                   18                24       Married  
4                   22                27        Single  
..                 ...               ...           ...  
195                 10                29       Married  
196                 12                15      Divorced  
197                 23                28      Divorced  
198                 21                 3       Married  
199                 19                 8        Single  

[200 rows x 12 columns]

In [10]:
df.head()

EmployeeID  Age              Department            JobRole Attrition  \
0        1001   50  Research & Development     Data Scientist        No   
1        1002   36  Research & Development     Data Scientist        No   
2        1003   29                   Sales     Data Scientist        No   
3        1004   42                   Sales         Sales Exec        No   
4        1005   40                   Sales  Software Engineer        No   

   MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0           8415              19                1                  4   
1           6391              19                3                  4   
2          14157              17                1                  4   
3          14835              13                3                  4   
4           8951              16                4                  3   

   PercentSalaryHike  DistanceFromHome MaritalStatus  
0                 16                20       Married  
1                 21                21       Married  
2                 22                18       Married  
3                 18                24       Married  
4                 22                27        Single

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   EmployeeID         200 non-null    int64 
 1   Age                200 non-null    int64 
 2   Department         200 non-null    object
 3   JobRole            200 non-null    object
 4   Attrition          200 non-null    object
 5   MonthlyIncome      200 non-null    int64 
 6   YearsAtCompany     200 non-null    int64 
 7   JobSatisfaction    200 non-null    int64 
 8   PerformanceRating  200 non-null    int64 
 9   PercentSalaryHike  200 non-null    int64 
 10  DistanceFromHome   200 non-null    int64 
 11  MaritalStatus      200 non-null    object
dtypes: int64(8), object(4)
memory usage: 18.9+ KB


### 2. Filter IT Department
Create a DataFrame `df_rd` containing only employees from the `'Research & Development'` department.

In [14]:

df_rd = df[df['Department'] == 'Research & Development'].copy()
df_rd

EmployeeID  Age              Department            JobRole Attrition  \
0          1001   50  Research & Development     Data Scientist        No   
1          1002   36  Research & Development     Data Scientist        No   
5          1006   44  Research & Development         HR Manager       Yes   
6          1007   32  Research & Development     Data Scientist        No   
8          1009   45  Research & Development     Data Scientist        No   
..          ...  ...                     ...                ...       ...   
193        1194   47  Research & Development     Data Scientist        No   
194        1195   24  Research & Development  Software Engineer        No   
195        1196   40  Research & Development         Sales Exec       Yes   
197        1198   53  Research & Development     Data Scientist        No   
199        1200   54  Research & Development         Sales Exec       Yes   

     MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0             8415              19                1                  4   
1             6391              19                3                  4   
5             8468               8                4                  3   
6            11007              19                2                  3   
8            12444               1                3                  3   
..             ...             ...              ...                ...   
193           8182              10                3                  4   
194          12916              16                1                  3   
195           9704               7                4                  3   
197          12984               7                3                  3   
199          14404              15                1                  3   

     PercentSalaryHike  DistanceFromHome MaritalStatus  
0                   16                20       Married  
1                   21                21       Married  
5                   12                11        Single  
6                   19                 2       Married  
8                   16                18       Married  
..                 ...               ...           ...  
193                 14                14       Married  
194                 10                27      Divorced  
195                 10                29       Married  
197                 23                28      Divorced  
199                 19                 8        Single  

[120 rows x 12 columns]

### 3. Salary Check
Find the employee with the highest `MonthlyIncome`. Display their `JobRole` and `MonthlyIncome`.

In [15]:
highest_income_employee = df.loc[df['MonthlyIncome'].idxmax()]
print(highest_income_employee[['JobRole', 'MonthlyIncome']])

JobRole          HR Manager
MonthlyIncome         14954
Name: 28, dtype: object


### 4. Missing Values
Check if there are any missing values (`NaN`) in the dataset.

In [16]:

missing_values = df.isnull().sum()
print(missing_values)

EmployeeID           0
Age                  0
Department           0
JobRole              0
Attrition            0
MonthlyIncome        0
YearsAtCompany       0
JobSatisfaction      0
PerformanceRating    0
PercentSalaryHike    0
DistanceFromHome     0
MaritalStatus        0
dtype: int64


### 5. Average Age by Role
Calculate the average `Age` for each `JobRole`.

In [17]:
avg_age_by_jobrole = df.groupby('JobRole')['Age'].mean().sort_values(ascending=False)
print(avg_age_by_jobrole)

JobRole
Sales Exec           44.000000
Software Engineer    40.395349
HR Manager           39.926829
Data Scientist       38.771429
Lab Technician       38.673469
Name: Age, dtype: float64


### 6. Attrition Count
How many employees have left the company? (Count values in the `Attrition` column).

In [18]:
attrition_counts = df['Attrition'].value_counts()
employees_left = attrition_counts.loc['Yes']
print(f"Employees who left: {employees_left}")

Employees who left: 33


### 7. High Performers
Filter for employees with `PercentSalaryHike` > 15 **AND** `PerformanceRating` == 4.

In [19]:
df_filtered = df[(df['PercentSalaryHike'] > 15) & (df['PerformanceRating'] == 4)].copy()


print(f"Number of Employees Meeting Both Criteria: {df_filtered.shape[0]}")


print(df_filtered.head())

Number of Employees Meeting Both Criteria: 27
    EmployeeID  Age              Department            JobRole Attrition  \
0         1001   50  Research & Development     Data Scientist        No   
1         1002   36  Research & Development     Data Scientist        No   
2         1003   29                   Sales     Data Scientist        No   
3         1004   42                   Sales         Sales Exec        No   
16        1017   59                   Sales  Software Engineer       Yes   

    MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0            8415              19                1                  4   
1            6391              19                3                  4   
2           14157              17                1                  4   
3           14835              13                3                  4   
16          10577               6                2                  4   

    PercentSalaryHike  DistanceFromHome MaritalStatus  
0 

### 8. Satisfaction Analysis (Pivot Table)
Create a pivot table showing the **average** `MonthlyIncome` for each `Department` (rows) broken down by `JobSatisfaction` (columns).

In [20]:
pivot_table_income = pd.pivot_table(
    df,
    values='MonthlyIncome',
    index='Department',
    columns='JobSatisfaction',
    aggfunc='mean'
)
print(pivot_table_income)

JobSatisfaction                    1            2            3            4
Department                                                                 
Human Resources          8494.666667  8822.200000  8196.333333  7744.833333
Research & Development  10810.718750  8581.125000  8648.090909  8930.304348
Sales                    9795.789474  9590.461538  8459.461538  9045.000000


### 9. Feature Engineering (Seniority)
Create a new column `Seniority`.
* If `YearsAtCompany` > 10, value is `'Senior'`
* Otherwise, value is `'Junior'`

Count how many Seniors vs Juniors there are.

In [21]:
import numpy as np


df['Seniority'] = np.where(df['YearsAtCompany'] > 10, 'Senior', 'Junior')


seniority_counts = df['Seniority'].value_counts()
print(seniority_counts)

Seniority
Junior    104
Senior     96
Name: count, dtype: int64


### 10. Retention Risk (Complex Filter)
Identify 'High Risk' employees who meet **ALL** these criteria:
1. `MaritalStatus` is 'Single'
2. `JobSatisfaction` is less than 3
3. `DistanceFromHome` > 10

Display their `EmployeeID` and `JobRole`.

In [22]:

condition_1 = df['MaritalStatus'] == 'Single'
condition_2 = df['JobSatisfaction'] < 3
condition_3 = df['DistanceFromHome'] > 10

df_high_risk = df[condition_1 & condition_2 & condition_3]

high_risk_employees = df_high_risk[['EmployeeID', 'JobRole']]
print(high_risk_employees)

     EmployeeID            JobRole
20         1021  Software Engineer
30         1031     Lab Technician
42         1043         HR Manager
43         1044         HR Manager
45         1046  Software Engineer
78         1079     Data Scientist
93         1094     Lab Technician
108        1109         Sales Exec
112        1113     Data Scientist
119        1120  Software Engineer
124        1125         HR Manager
159        1160         HR Manager
161        1162     Data Scientist
168        1169         HR Manager
169        1170         Sales Exec
172        1173  Software Engineer
174        1175         HR Manager
183        1184     Lab Technician
185        1186     Data Scientist
